export const data = {
    lte: [
      "0xB060 LTE MAC Configuration [Version 1]",
      "0xB061 LTE MAC Rach Trigger [Version 1]",
      "0xB062 LTE MAC Rach Attempt [Version 1]",
      "0xB063 LTE MAC DL Transport Block [Mismatched Version: 1, 50 (db) vs 1, 48 (packet class)]",
      "0xB064 LTE MAC UL Transport Block [Version 1]"
    ],
    "5g": {
      type1: [
        "0xB06E LTE MAC DL RAR Transport Block [Version 48]",
        "0xB081 LTE RLC DL Config Log packet  [Version 1, 49]",
        "0xB082 LTE RLC DL AM All PDU [Mismatched Version: 1, 48 (db) vs 1, N/A (packet class)]",
        "0xB083 LTE RLC DL AM Control PDU [Version 1, 48]"
      ],
      type2: [
        "0xB086 LTE RLC DL UM Data PDU [Version 1]",
        "0xB087 LTE RLC DL Statistics [Mismatched Version: 1, 49 (db) vs 1, 1 (packet class)]",
        "0xB089 LTE RLC eMBMS DATA PDU [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]",
        "0xB08A LTE RLC eMBMS Statistics [Version 1, 48]"
      ]
    }
  };
  